import {
  FormatListBulleted as TodoIcon,
  Calculate as CalculateIcon,
  CurrencyExchange as CurrencyIcon,
  Code as JsonIcon,
  Lock as KeyGenIcon,
  Translate as Base64Icon,
  Key as JwtIcon,
  Google as GoogleIcon,
  CalendarMonth as CalendarIcon,
  CompareArrows as CompareIcon,
} from '@mui/icons-material'

export const TOOLS_CONFIG = [
  {
    id: 'todo',
    title: 'Todo Manager',
    description: 'Organize your tasks and projects efficiently',
    icon: TodoIcon,
    path: '/tools/todo',
  },
  {
    id: 'love-diary',
    title: 'Love Diary',
    description: 'Capture and cherish your memories',
    icon: TodoIcon,
    path: '/tools/love-diary',
  },
  {
    id: 'calendar',
    title: 'Class Calendar',
    description: 'Manage your teaching schedule and track earnings',
    icon: CalendarIcon,
    path: '/tools/calendar',
  },
  {
    id: 'salary-calculator',
    title: 'Salary Calculator',
    description: 'Calculate multiple country tax and after tax salary',
    icon: CalculateIcon,
    path: '/tools/salary-calculator',
  },
  {
    id: 'currency-exchange',
    title: 'Currency Exchange',
    description: 'Have a quick look for the currency exchange rates',
    icon: CurrencyIcon,
    path: '/tools/currency-exchange',
  },

  {
    id: 'loan-calculator',
    title: 'Loan Calculator',
    description: 'Calculate loan payments with support for CNY and AUD currencies',
    icon: CalculateIcon,
    path: '/tools/loan-calculator',
  },
  {
    id: 'code-compare',
    title: 'Code Compare',
    description: 'Show Code diffs',
    icon: CompareIcon,
    path: '/tools/code-compare',
  },
  {
    id: 'json-formatter',
    title: 'JSON Formatter',
    description: 'Format and validate JSON data',
    icon: JsonIcon,
    path: '/tools/json-formatter',
  },
  {
    id: 'base64',
    title: 'Base64 Converter',
    description: 'Encode and decode Base64 strings',
    icon: Base64Icon,
    path: '/tools/base64',
  },
  {
    id: 'session-key',
    title: 'Session Key Generator',
    description: 'Generate secure session keys',
    icon: KeyGenIcon,
    path: '/tools/session-key',
  },
  {
    id: 'jwt-config',
    title: 'JWT Configuration',
    description: 'Generate JWT configuration and keys',
    icon: JwtIcon,
    path: '/tools/jwt-config',
  },
  {
    id: 'google-oauth',
    title: 'Google OAuth Setup',
    description: 'Configure Google OAuth credentials',
    icon: GoogleIcon,
    path: '/tools/google-oauth',
  },
]
